### ISSUE TITLE
[related-publications]

### ISSUE THREAD

**Issue by avlukanin** [UnitexGramLab/unitexgramlab-org#22]
Sabirova, K., Lukanin, A. (2014) Automatic Extraction of Hypernyms and Hyponyms from Russian
Texts. In: Supplementary Proceedings of the 3rd International Conference on Analysis
of Images, Social Networks and Texts (AIST'2014), vol. 1197, pp. 35-40. CEUR-WS,
Yekaterinburg

Lukanin A. (2015) Normalization of Non-standard Words with Finite State Transducers for Russian Speech Synthesis. In: Khachay M., Konstantinova N., Panchenko A., Ignatov D., Labunets V. (eds) Analysis of Images, Social Networks and Texts. Communications in Computer and Information Science, vol 542. Springer, Cham

**Comment by martinec** [comment]
Hi @avlukanin,  I was wondering if you can share the entries in BibTeX format?

**Comment by avlukanin** [comment]
Google Scholar provides these entries:

```
@inproceedings{sabirova2014automatic,
  title={Automatic Extraction of Hypernyms and Hyponyms from Russian Texts.},
  author={Sabirova, Kristina and Lukanin, Artem},
  booktitle={AIST (Supplement)},
  pages={35--40},
  year={2014}
}
```

```
@inproceedings{lukanin2015normalization,
  title={Normalization of Non-standard Words with Finite State Transducers for Russian Speech Synthesis},
  author={Lukanin, Artem},
  booktitle={International Conference on Analysis of Images, Social Networks and Texts},
  pages={39--48},
  year={2015},
  organization={Springer International Publishing}
}
```
